[workspace]
authors = ["Blair-Johnson <blairjohnson@gatech.edu>"]
channels = ["conda-forge"]
name = "DRUM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.7.*"
cudatoolkit = "10.0.*"
cudnn = "7.*"
protobuf = "<=3.20"

[pypi-dependencies]
tensorflow-gpu = "==1.13.1"
